# Path to an uncompressed FASTA file with all chromosome sequences.
DNA: '/data/srlab/slowikow/src/snakefiles/data/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa'

# Path to an uncompressed GTF file with all gene annotations.
GTF: '/data/srlab/slowikow/src/snakefiles/data/ensembl/Homo_sapiens.GRCh38.82.gtf'

# Path to a folder where intermediate files will be written.
OUT_DIR: '/data/srlab/slowikow/src/snakefiles/star_express'

# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES_JSON: '../samples.json'
